/*
 * Main.java
 */
package net.ausiasmarch.estadistica.gui;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.ausiasmarch.estadistica.modelo.Estadistica;
import net.ausiasmarch.common.Convert;
import net.ausiasmarch.estadistica.modelo.*;

/**
 *
 * @author Adrian Garcia
 */
public class Main extends javax.swing.JFrame {

    //Permite que la ciudad tenga validos esos caracteres
    private final String exprReg = "[A-Za-zÁÉÍÓÚáéíóúñÑ]+(\\s[A-Za-zÁÉÍÓÚáéíóúñÑ]+)*";
    
    private final List<Ciudad> ciudades;

    private final Estadistica estadistica;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        ciudades = new ArrayList<>();
        estadistica = new Estadistica();
        
        setSize(690,670);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHabitantes = new javax.swing.JTextField();
        jButtonBuscarCiudad = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumHabitantes = new javax.swing.JTextField();
        jButtonBuscarNumHab = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTotalCiudades = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumCiudades = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMedia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldHabitantesMin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCiudadPobMax = new javax.swing.JTextField();
        jTextFieldCiudadPobMin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldHabitantesMax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCiudades = new javax.swing.JTextArea();
        jButtonCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBorrado = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonOrdenarDesc = new javax.swing.JButton();
        jButtonOrdenarAsc = new javax.swing.JButton();
        jButtonOrdenarNombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ciudades");

        jTextFieldCiudad.setToolTipText("Nombre de la ciudad");

        jLabel1.setText("Ciudad");

        jButtonAgregar.setText("Añadir");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel2.setText("Ciudad");

        jLabel4.setText("Habitantes:");

        jTextFieldHabitantes.setEditable(false);
        jTextFieldHabitantes.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldHabitantes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonBuscarCiudad.setText("Buscar");
        jButtonBuscarCiudad.setEnabled(false);
        jButtonBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCiudadActionPerformed(evt);
            }
        });

        jLabel7.setText("Habitantes");

        jButtonBuscarNumHab.setText("Buscar");
        jButtonBuscarNumHab.setEnabled(false);
        jButtonBuscarNumHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNumHabActionPerformed(evt);
            }
        });

        jLabel8.setText("Total ciudades");

        jTextFieldTotalCiudades.setEditable(false);
        jTextFieldTotalCiudades.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldTotalCiudades.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBusqueda)
                    .addComponent(jTextFieldNumHabitantes, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarNumHab)
                    .addComponent(jButtonBuscarCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotalCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCiudad)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldNumHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldTotalCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonBuscarNumHab)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información estadística"));

        jLabel5.setText("Nº de Ciudades:");

        jTextFieldNumCiudades.setEditable(false);
        jTextFieldNumCiudades.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNumCiudades.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Media de población");

        jTextFieldMedia.setEditable(false);
        jTextFieldMedia.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldMedia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("Ciudad Población mínima");

        jTextFieldHabitantesMin.setEditable(false);
        jTextFieldHabitantesMin.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldHabitantesMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHabitantesMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHabitantesMinActionPerformed(evt);
            }
        });

        jLabel11.setText("Ciudad Población máxima");

        jTextFieldCiudadPobMax.setEditable(false);
        jTextFieldCiudadPobMax.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCiudadPobMax.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldCiudadPobMin.setEditable(false);
        jTextFieldCiudadPobMin.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCiudadPobMin.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setText("Habitantes");

        jLabel13.setText("Habitantes");

        jTextFieldHabitantesMax.setEditable(false);
        jTextFieldHabitantesMax.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldHabitantesMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Habitantes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldNumCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldCiudadPobMax, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCiudadPobMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHabitantesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldHabitantesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNumCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCiudadPobMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCiudadPobMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHabitantesMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel6.setText("Población");

        jTextFieldPoblacion.setToolTipText("Número de habitantes");

        jLabel15.setText("habitantes");

        jLabel16.setText("Lista de ciudades - CIUDAD (Población)");

        jTextAreaCiudades.setEditable(false);
        jTextAreaCiudades.setBackground(new java.awt.Color(255, 255, 204));
        jTextAreaCiudades.setColumns(20);
        jTextAreaCiudades.setLineWrap(true);
        jTextAreaCiudades.setRows(5);
        jTextAreaCiudades.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaCiudades);

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setEnabled(false);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabel3.setText("Borrar la ciudad");

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setEnabled(false);
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar todo");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonOrdenarDesc.setText("Ordenar de mayor a menor población");
        jButtonOrdenarDesc.setEnabled(false);
        jButtonOrdenarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarDescActionPerformed(evt);
            }
        });

        jButtonOrdenarAsc.setText("Ordenar de menor a mayor población");
        jButtonOrdenarAsc.setEnabled(false);
        jButtonOrdenarAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombre.setText("Ordenar por nombre");
        jButtonOrdenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15))
                            .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(268, 268, 268))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOrdenarAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOrdenarDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOrdenarNombre)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(275, 275, 275))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBorrar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrdenarDesc)
                    .addComponent(jButtonOrdenarAsc)
                    .addComponent(jButtonOrdenarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonSalir))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed

        String sCiudad = jTextFieldCiudad.getText();
        String sPoblacion = jTextFieldPoblacion.getText();
        int habitantes;
        Ciudad ciudad;

        if (!validaNombreCiudad(sCiudad)) {
            return;
        }

        if (!Convert.isValidInt(sPoblacion)) {
            mensaje("El número de habitantes no es valido");
            return;
        }
        habitantes = Convert.parseInt(sPoblacion);

        //Limpiar datos
        jTextFieldCiudad.setText("");
        jTextFieldPoblacion.setText("");
        
        //Añadir ciudad y habitantes a la lista:
        
        ciudad = new Ciudad(sCiudad,habitantes);
        
        ciudades.add(ciudad);        

        if (!ciudades.isEmpty()) {
            mostrarCiudades(ciudades);
            botonesOnOff(true);           
        }
        
        //Le pasamos a estadistica la lista de ciudades
        estadistica.setCiudades(ciudades);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void botonesOnOff(boolean sn) {
        jButtonCalcular.setEnabled(sn);
        jButtonBorrar.setEnabled(sn);
        jButtonBuscarCiudad.setEnabled(sn);
        jButtonBuscarNumHab.setEnabled(sn);
        jButtonOrdenarAsc.setEnabled(sn);
        jButtonOrdenarDesc.setEnabled(sn);
        jButtonOrdenarNombre.setEnabled(sn);
    }

    private void mostrarCiudades(List<Ciudad> ciudades) {
        StringBuilder sb = new StringBuilder();
        for (Ciudad c : ciudades) {
            sb.append(c.toString());
            sb.append("\n");
        }
        jTextAreaCiudades.setText(sb.toString());
    }

    private boolean validaNombreCiudad(String nombre) {
        if (!nombre.trim().matches(exprReg)) {
            mensaje("El nombre de la ciudad no es valido");
            return false;
        }
        return true;
    }

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        String nombre = jTextFieldBorrado.getText().toUpperCase();

        if (!validaNombreCiudad(nombre)) {
            return;
        }
        
        if (!estadistica.borrarCiudad(nombre)){
            mensaje("No se encuentra " + nombre);
            return;
        }
        
        //Ahora se tiene que borrar la ciudad de la lista de arriba y actualizarse
        jTextFieldBorrado.setText("");
        mostrarCiudades(ciudades);
        
    /*
        Ahora limpiaremos la lista y borramos
        */
        if (ciudades.isEmpty()){
            botonesOnOff(false);
           // limpiarCampos();
            // jTextField____("");
        }             
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        
        //a cada metodo lo llamamos numCiudades y media respectivamente en lugar de get....
        int numCiudades = estadistica.getNumCiudades();
        double media = estadistica.getMediaHabitantes();
        
        jTextFieldNumCiudades.setText(Convert.format(numCiudades));
        jTextFieldMedia.setText(Convert.format(media));
        
        /*Llamar a los metodos MIN y MAX para que muestre la ciudad con menor numeros de habitantes 
                y la mayor numero de habitantes
                */
        //creamos dos variables de ciudad min, max        
        Ciudad min, max;
        
        min = estadistica.getCiudadMenorHabitantes();
        max = estadistica.getCiudadMayorHabitantes();
        
        //CIUDAD MINIMIA:
        jTextFieldCiudadPobMin.setText(min.getNombre());
        jTextFieldHabitantesMin.setText(Convert.format(min.getHabitantes()));
        
        //CIUDAD MAXIMA:
        jTextFieldCiudadPobMax.setText(max.getNombre());
        jTextFieldHabitantesMax.setText(Convert.format(max.getHabitantes()));
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCiudadActionPerformed

        String nombre = jTextFieldBusqueda.getText().toUpperCase();

        if ((!validaNombreCiudad(nombre))) {
            return;
        }     
        
    //Metodo que devuelve el indice de la ciudad correspondiente:
        int valor = estadistica.buscarCiudad(nombre);
        
        if (valor < 0) {
            mensaje ("No se encuentra " + nombre);
            return;                   
    }//GEN-LAST:event_jButtonBuscarCiudadActionPerformed
   
        jTextFieldHabitantes.setText(Convert.format(ciudades.get(valor).getHabitantes()));
    }
    
    private void jButtonBuscarNumHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNumHabActionPerformed
        //Validamos para que solo se introduzca valor NUMER
        if (!Convert.isValidInt(jTextFieldNumHabitantes.getText())) {
            mensaje("Numero de habitantes no valido");
            return;
        }
    
        //Convertirmos a 
        int valor = Convert.parseInt(jTextFieldNumHabitantes.getText());
        int total = estadistica.ciudadesConHabitantes(valor);
        
        if (total == 0 ) {
            mensaje ("No se encontraron ciudades con " + valor + " habitantes");
            return;
        }
        //En caso de que no devuelva 0, MOSTRAR LAS CIUDADES
        jTextFieldTotalCiudades.setText(Convert.format(total));
        
    }//GEN-LAST:event_jButtonBuscarNumHabActionPerformed

    private void jTextFieldHabitantesMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHabitantesMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHabitantesMinActionPerformed

    private void jButtonOrdenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreActionPerformed
        estadistica.ordenarPorNombreAsc();
        mostrarCiudades(ciudades);
    }//GEN-LAST:event_jButtonOrdenarNombreActionPerformed

    private void jButtonOrdenarAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarAscActionPerformed
        // Llamar al metodo de ordenar por Habitante ascendente y mostrar Ciudad de Main
        estadistica.ordenarPorHabitanteAsc();
        mostrarCiudades(ciudades);        
    }//GEN-LAST:event_jButtonOrdenarAscActionPerformed

    private void jButtonOrdenarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarDescActionPerformed
        // Llamar al metodo de ordenar por HABITANTE DESC y Mostrar CIUDADES de MAIN
        estadistica.ordenarPorHabitanteDesc();
        mostrarCiudades(ciudades);
    }//GEN-LAST:event_jButtonOrdenarDescActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextAreaCiudades.setText("");
        jTextFieldBorrado.setText("");
        jTextFieldBusqueda.setText("");
        jTextFieldCiudad.setText("");
        jTextFieldCiudadPobMax.setText("");
        jTextFieldCiudadPobMin.setText("");
        jTextFieldHabitantes.setText("");
        jTextFieldHabitantesMax.setText("");
        jTextFieldHabitantesMin.setText("");
        jTextFieldMedia.setText("");
        jTextFieldNumCiudades.setText("");
        jTextFieldNumHabitantes.setText("");
        jTextFieldPoblacion.setText("");
        jTextFieldTotalCiudades.setText("");
        
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            String look = UIManager.getSystemLookAndFeelClassName();
            javax.swing.UIManager.setLookAndFeel(look);
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if (info.getName().equals(("Windows"))) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscarCiudad;
    private javax.swing.JButton jButtonBuscarNumHab;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonOrdenarAsc;
    private javax.swing.JButton jButtonOrdenarDesc;
    private javax.swing.JButton jButtonOrdenarNombre;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCiudades;
    private javax.swing.JTextField jTextFieldBorrado;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldCiudadPobMax;
    private javax.swing.JTextField jTextFieldCiudadPobMin;
    private javax.swing.JTextField jTextFieldHabitantes;
    private javax.swing.JTextField jTextFieldHabitantesMax;
    private javax.swing.JTextField jTextFieldHabitantesMin;
    private javax.swing.JTextField jTextFieldMedia;
    private javax.swing.JTextField jTextFieldNumCiudades;
    private javax.swing.JTextField jTextFieldNumHabitantes;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldTotalCiudades;
    // End of variables declaration//GEN-END:variables
}
